project:
  type: website

website:
  title: "Mason Reece"
  description: "PhD Candidate in Political Science at MIT"
  page-navigation: true
  back-to-top-navigation: false
  search: false

  page-footer:
    left: >-
     &#169; 2024 Mason Reece &#8729; Made with [Quarto](https://quarto.org); Inspired by [Silvia Canelón](https://silviacanelon.com/) and [Shiro Kuriwaki's](https://www.shirokuriwaki.com/) websites
    right: >-
      [mpreece (at) mit (dot) edu](mailto:mpreece@mit.edu)

format:
  html:
    theme: cosmo
    code-link: true
    pagetitle: "Mason Reece | {{< meta title >}}"
    lightbox: true

execute:
  freeze: auto