project:
  type: website
  resources:
    - files/

website:
  title: "Mason Reece"
  description: "PhD Candidate in Political Science at MIT"
  search: false

format:
  html:
    theme: cosmo
    lightbox: true